mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    # url: jdbc:mysql://192.168.3.21:3306/rongxintianxia?useUnicode=true&amp;characterEncoding=UTF-8
    url: jdbc:mysql//localhost:3306/test?useUnicode=true&amp;characterEncoding=UTF-8
    driverclassname: com.mysql.jdbc.Driver
    username: root
    password:
