hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  #设置API网关中路由转发请求的HystrixCommand执行超时时间
ribbon:
  ConnectTimeout: 3000 #设置路由转发请求的时候，创建请求连接的超时时间
  ReadTimeout: 60000  #用来设置路由转发请求的超时时间

server:
  port: 9527

spring:
  application:
    name: demo-zuul
  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 60000  #设置API网关中路由转发请求的HystrixCommand执行超时时间
  ribbon:
    ConnectTimeout: 3000 #设置路由转发请求的时候，创建请求连接的超时时间
    ReadTimeout: 60000  #用来设置路由转发请求的超时时间

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8890/eureka/

zuul:
  routes:
    user-route:                   # 该配置方式中，user-route只是给路由一个名称，可以任意起名。
      service-id: demo-p2
      path: /dp2/**              # service-id对应的路径
  prefix: /demo
  ignored-services: "*"

